# This is a basic workflow to help you get started with Actions

name: CI

on: issue_comment

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Ton problème à été enregistré
        
